### PR TITLE
Converted math parser to .net core

### PR DESCRIPTION
**Pull request by dagrooms52**
You will have to open this with VS 2017. The new csproj style does not build in VS 2015
Char.ToString does not take CultureInfo now - could not find an override, I'll look for possible external packages and follow up.
Realized in the diff there is a whitespace issue (MathParser.cs) - what are your line endings? I'm forcing Windows line endings through git.

### CODE REVIEW

**Comment by dagrooms52** [comment]
Oh yeah - your CI is going to need to handle .NET Core as well. Sadly I can't PR that fix.

**Comment by dagrooms52** [comment]
As far as backwards compatibility goes, I'm sure you'll want this PR project as a copy instead of a replacement of the main project. I've seen msbuild tasks to generate different projects with different targets, but only in .net framework to PCL, not .net framework to .net core. Might play around with it and see if I get anything workable.

**Comment by napen123** [comment]
This looks fine to me, and I agree that this should be separate from the main library. I'm fine with upgrading to VS 2017. What do you think, @artemlos ? (Also, I use windows line-endings.)

**Comment by dagrooms52** [comment]
This one should work better: https://github.com/MathosProject/Mathos-Parser/pull/11

**Pull request closed without merging**
