### PR TITLE
Replace double with decimal

### PR DESCRIPTION
**Pull request by napen123**
Thought we should just merge the branches.

### CODE REVIEW

**Comment by artemlos** [comment]
sounds good. it would be good to see what can be done about the new way of expressing numbers first, i.e.using scientific notation.

**Comment by artemlos** [comment]
@napen123 , are you able to see the Travis CI build results above?

**Comment by napen123** [comment]
yes, I'm able to. Do you think we should add travis builds?

**Comment by artemlos** [comment]
Did you try it using the old parser or the new one (in rework)? Yes, we could you use Travis build! :)

**Comment by napen123** [comment]
I used the one in rework. I also managed to get Travis to work!

**Comment by artemlos** [comment]
Great Ethan! :)

**Pull request merged**
